#!/bin/bash
set -e

case "$1" in
    purge)
        # On purge, remove configs from /etc/skel/ but NOT from user home directories
        # User configs are preserved
        echo "wlanpi-shell-config purged"
        ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # On remove/upgrade, do nothing - preserve user configs
        ;;
esac

exit 0
